"""initial_10_tables

Revision ID: b2721f5aa81f
Revises: None
Create Date: 2026-09-25 23:11:45.051876

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import backend.app.models.base

# revision identifiers, used by Alembic.
revision: str = 'b2721f5aa81f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('language_pref', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('session_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_session_id'), 'audit_events', ['session_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('session_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('internal_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('type_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('situation_context', sa.String(length=500), nullable=True),
    sa.Column('delete_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_delete_after'), 'documents', ['delete_after'], unique=False)
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('situations',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('session_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('description_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('clarifying_questions', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('delete_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_situations_delete_after'), 'situations', ['delete_after'], unique=False)
    op.create_index(op.f('ix_situations_session_id'), 'situations', ['session_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('document_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=False),
    sa.Column('urgency_reason', sa.String(length=500), nullable=False),
    sa.Column('urgency_date', sa.Date(), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), nullable=False),
    sa.Column('high_risk_category', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('dropped_item_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uncertainty', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_document_id'), 'analyses', ['document_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('document_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('document_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('content_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('sanitised', sa.Boolean(), nullable=False),
    sa.Column('injection_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=True)
    op.create_table('jobs',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('document_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_document_id'), 'jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('analysis_items',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('analysis_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_items_analysis_id'), 'analysis_items', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_items_type'), 'analysis_items', ['type'], unique=False)
    op.create_table('source_spans',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('item_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('quoted_text', sa.String(length=2000), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['analysis_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_spans_item_id'), 'source_spans', ['item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_spans_item_id'), table_name='source_spans')
    op.drop_table('source_spans')
    op.drop_index(op.f('ix_analysis_items_type'), table_name='analysis_items')
    op.drop_index(op.f('ix_analysis_items_analysis_id'), table_name='analysis_items')
    op.drop_table('analysis_items')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_document_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_analyses_document_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_situations_session_id'), table_name='situations')
    op.drop_index(op.f('ix_situations_delete_after'), table_name='situations')
    op.drop_table('situations')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_delete_after'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_session_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
